// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDslMehha5egN7FbmMlNdfHwpl-zrXsjp8',
    appId: '1:425513032535:web:2ef24f4b6bb270c5ac7c12',
    messagingSenderId: '425513032535',
    projectId: 'tetris2-3f58d',
    authDomain: 'tetris2-3f58d.firebaseapp.com',
    storageBucket: 'tetris2-3f58d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnkWf4IU00RoXIg15ST8xF3xcS1ROvVjc',
    appId: '1:425513032535:android:6088ea4dff67e46bac7c12',
    messagingSenderId: '425513032535',
    projectId: 'tetris2-3f58d',
    storageBucket: 'tetris2-3f58d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDa3JrsTubpYzzL-80IDpvl0bg6w7Yc45g',
    appId: '1:425513032535:ios:234b0ba909dfe7a3ac7c12',
    messagingSenderId: '425513032535',
    projectId: 'tetris2-3f58d',
    storageBucket: 'tetris2-3f58d.appspot.com',
    iosBundleId: 'gr.techzombie.tetris',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDa3JrsTubpYzzL-80IDpvl0bg6w7Yc45g',
    appId: '1:425513032535:ios:61e13eec097ffb6fac7c12',
    messagingSenderId: '425513032535',
    projectId: 'tetris2-3f58d',
    storageBucket: 'tetris2-3f58d.appspot.com',
    iosBundleId: 'gr.techzombie.tetris.RunnerTests',
  );
}
